<?php

namespace AclBundle\Repository;

/**
 * ObjetoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjetoRepository extends \Doctrine\ORM\EntityRepository
{
}
